IF NOT EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) = 'RDS_SRCSSIMS' AND name = 'APVMAS') 
CREATE TABLE RDS_SRCSSIMS.APVMAS (
CORP string,
VEND_NUM string,
VEND_SUB_ACNT string,
NAME string,
ADDR1 string,
ADDR2 string,
POSTAL_CD string,
PHONE_NUM string,
VEND_TYPE string,
EDI_MAILBOX string,
EDI_VEND_ACNT_NUM string,
AP_CLASS string,
PAYEE_SUB_ACNT string,
SEND_DM_PAYEE_IND string,
BACKHAUL_IND string,
AP_DIV string,
AP_VEND_NUM string,
AP_PAY_PO_SW string,
AP_CLERK_NUM string,
WHSE_XFER_SW string,
COUNTRY_CODE string,
FAX_1_NUM string,
FAX_2_NUM string,
CATLG_DISTR_SW string,
EDI_BR_ITEM_CD_SW string,
VEND_DUNS_AND_SUFX string,
PROV_CD string,
DISTRIB_TYPE string,
VENDOR_STATUS string,
DSD_AUTOPAY_VEN_SW string,
DSD_CMP_CST_SW string,
DROP_SHIP_DISTR_SW string,
	LAST_FM_DATE date NOT NULL,
	PRIMARY_SMIC int, NOT NULL,
AR_ACCT string,
AR_SUB_ACCT string,
DL_SHRT_BILL_AUTH string,
ALLOW_BILL_MTD string,
BB_ALLOW_BILL_MTD string,
DL_SHRT_BILL_MTD string,
O_INV_ALW_BL_MTD string,
VND_FL_ALW_BL_MTD string,
DM_PROCESS_SYS_IND string,
ITM_FL_ALW_BL_MTD string,
PRODUCT_LINE_SW string,
	DFLT_MARKON_FCTR bigbignumeric, NOT NULL,
	AP_FLOAT_DAYS bigbignumeric, NOT NULL,
DSD_OFFICE_INV_SW string,
CONTACT string,
AUTOMATCH_IND string,
EDI_CRP_ACNT_NUM string,
INTERCO_MEMO_IND string,
ACTHFLAG_, string,
BCOSTSW string,
EDI_CONTACT_NM string,
EDI_FAX_NBR string,
GST_RST_NBR string,
GST_RST_SW string,
BYPASS_FRIDAY_SW string,
EDI_REJ_MTD_IND string,
DSD_RPT_SCHED_CD string,
EDI_FRCST_ACCT_ID string,
BIO_TERROR_RST_IND string,
	SETUP_DATE date NOT NULL,
UPD_BY string,
SETUP_BY_USER_ID string,
EDI_WHSE_ADVC_ID string,
ISP_PROVIDER_IND string,
SWY_IOR_IND string,
ORIG_DST_CNTR string,
DSD_EDI_STR_ORD_SW string,
created_by varstring,
	created_dt datetime DEFAULT CONVERT([datetime],CONVERT([datetime],(sysdatetimeoffset() AT TIME ZONE 'Mountain Standard Time'))) NOT NULL,
modified_by varstring,
	modified_dt datetime NULL
);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME =  ,)
 CREATE  UNIQUE CLUSTERED INDEX APVMASIDX1 ON RDS_SRCSSIMS.APVMAS (  CORP ASC  , VEND_NUM ASC  , VEND_SUB_ACNT ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = ,   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME =  ,)
 CREATE  NONCLUSTERED INDEX APVMASIDX2 ON RDS_SRCSSIMS.APVMAS (  modified_dt ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = ,   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME =  ,)
 CREATE  NONCLUSTERED INDEX APVMASIDX3 ON RDS_SRCSSIMS.APVMAS (  VEND_NUM ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = ,   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
GO

