IF NOT EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) = 'RDS_SRCSSIMS' AND name = 'APVMAS') 
CREATE TABLE RDS_SRCSSIMS.APVMAS (
	CORP nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	VEND_NUM nvarchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	VEND_SUB_ACNT nvarchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	NAME nvarchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ADDR1 char(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ADDR2 char(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	POSTAL_CD char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PHONE_NUM char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	VEND_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_MAILBOX char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_VEND_ACNT_NUM char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AP_CLASS nvarchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PAYEE_SUB_ACNT char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SEND_DM_PAYEE_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BACKHAUL_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AP_DIV char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AP_VEND_NUM char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AP_PAY_PO_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AP_CLERK_NUM char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	WHSE_XFER_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	COUNTRY_CODE char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FAX_1_NUM char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FAX_2_NUM char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CATLG_DISTR_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_BR_ITEM_CD_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	VEND_DUNS_AND_SUFX nvarchar(13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PROV_CD char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DISTRIB_TYPE char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	VENDOR_STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DSD_AUTOPAY_VEN_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DSD_CMP_CST_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DROP_SHIP_DISTR_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LAST_FM_DATE date NOT NULL,
	PRIMARY_SMIC smallint NOT NULL,
	AR_ACCT char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AR_SUB_ACCT char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DL_SHRT_BILL_AUTH char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ALLOW_BILL_MTD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BB_ALLOW_BILL_MTD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DL_SHRT_BILL_MTD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	O_INV_ALW_BL_MTD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	VND_FL_ALW_BL_MTD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DM_PROCESS_SYS_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ITM_FL_ALW_BL_MTD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PRODUCT_LINE_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DFLT_MARKON_FCTR decimal(5,3) NOT NULL,
	AP_FLOAT_DAYS decimal(3,0) NOT NULL,
	DSD_OFFICE_INV_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONTACT char(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	AUTOMATCH_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_CRP_ACNT_NUM char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	INTERCO_MEMO_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ACTHFLAG_01 char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BCOSTSW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_CONTACT_NM char(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_FAX_NBR char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GST_RST_NBR char(9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	GST_RST_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BYPASS_FRIDAY_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_REJ_MTD_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DSD_RPT_SCHED_CD char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_FRCST_ACCT_ID char(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	BIO_TERROR_RST_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SETUP_DATE date NOT NULL,
	UPD_BY char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SETUP_BY_USER_ID char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	EDI_WHSE_ADVC_ID char(15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ISP_PROVIDER_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	SWY_IOR_IND char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	ORIG_DST_CNTR char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	DSD_EDI_STR_ORD_SW char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	created_by varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS DEFAULT 'system' NOT NULL,
	created_dt datetime2 DEFAULT CONVERT([datetime2],CONVERT([datetime2],(sysdatetimeoffset() AT TIME ZONE 'Mountain Standard Time'))) NOT NULL,
	modified_by varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	modified_dt datetime2 NULL
);
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME =  'APVMASIDX1')
 CREATE  UNIQUE CLUSTERED INDEX APVMASIDX1 ON RDS_SRCSSIMS.APVMAS (  CORP ASC  , VEND_NUM ASC  , VEND_SUB_ACNT ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME =  'APVMASIDX2')
 CREATE  NONCLUSTERED INDEX APVMASIDX2 ON RDS_SRCSSIMS.APVMAS (  modified_dt ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
GO

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE NAME =  'APVMASIDX3')
 CREATE  NONCLUSTERED INDEX APVMASIDX3 ON RDS_SRCSSIMS.APVMAS (  VEND_NUM ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 90   ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
GO

